"""Stack-driven coding scaffold builder for Foxforge-code."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
import json
import shutil
from pathlib import Path
from typing import Any, Callable

from shared_tools.stack_catalog import derive_project_type, stack_key


@dataclass(slots=True)
class BuildResult:
    success: bool
    message: str
    path: str
    files_written: list[str]


def _safe_read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return ""


def _render_template(content: str, *, context: dict[str, str]) -> str:
    out = content
    for key, value in context.items():
        out = out.replace("{{" + key + "}}", value)
    return out


def _copy_scaffold(scaffold_root: Path, target_root: Path, *, context: dict[str, str]) -> list[str]:
    files_written: list[str] = []
    for src in scaffold_root.rglob("*"):
        if src.is_dir():
            continue
        rel = src.relative_to(scaffold_root)
        dst = target_root / rel
        dst.parent.mkdir(parents=True, exist_ok=True)

        text = _safe_read_text(src)
        if text:
            dst.write_text(_render_template(text, context=context), encoding="utf-8")
        else:
            shutil.copy2(src, dst)
        files_written.append(str(rel))
    return sorted(files_written)


def build(project: dict[str, Any], plan: str, *, repo_root: Path) -> BuildResult:
    slug = str(project.get("slug") or "project").strip() or "project"
    name = str(project.get("name") or slug).strip() or slug
    stack = dict(project.get("stack") or {})
    workspace_path = str(project.get("workspace_path") or "").strip()
    if workspace_path:
        workspace = Path(workspace_path).expanduser()
    else:
        workspace = repo_root / "Projects" / slug

    workspace.mkdir(parents=True, exist_ok=True)

    key = stack_key(stack)
    scaffold_root = repo_root / "SourceCode" / "scaffolds" / key
    project_type = derive_project_type(stack)
    context = {
        "project_name": name,
        "project_slug": slug,
        "project_type": project_type,
        "backend": str(stack.get("backend") or ""),
        "frontend": str(stack.get("frontend") or ""),
        "database": str(stack.get("database") or ""),
        "language": str(stack.get("language") or ""),
        "db_url": str(project.get("db_url") or "sqlite:///app.db"),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "plan": plan,
    }

    files_written: list[str]
    if scaffold_root.exists():
        files_written = _copy_scaffold(scaffold_root, workspace, context=context)
        msg = f"Scaffold '{key}' generated."
    else:
        readme = workspace / "README.md"
        readme.write_text(
            "\n".join(
                [
                    f"# {name}",
                    "",
                    "Generated by Foxforge-code stack builder.",
                    "",
                    "## Stack",
                    "```json",
                    json.dumps(stack, indent=2, sort_keys=True),
                    "```",
                    "",
                    "## Plan",
                    plan.strip() or "(none)",
                ]
            ),
            encoding="utf-8",
        )
        files_written = ["README.md"]
        msg = f"No scaffold found for '{key}', created fallback README."

    return BuildResult(
        success=True,
        message=msg,
        path=str(workspace),
        files_written=files_written,
    )


def run_stack_builder_pool(
    *,
    question: str,
    repo_root: Path,
    project_slug: str,
    bus,
    research_context: str = "",
    plan_text: str = "",
    stack: dict[str, Any] | None = None,
    workspace_path: str = "",
    cancel_checker: Callable[[], bool] | None = None,
    progress_callback: Callable[[str, dict[str, Any]], None] | None = None,
) -> dict[str, Any]:
    if cancel_checker and cancel_checker():
        return {
            "ok": False,
            "error": "cancelled",
            "message": "Request cancelled before stack build started.",
        }

    if progress_callback:
        progress_callback("stack_builder_started", {"project": project_slug})

    project = {
        "slug": project_slug,
        "name": project_slug.replace("-", " ").title(),
        "stack": dict(stack or {}),
        "workspace_path": workspace_path,
    }

    combined_plan = "\n\n".join(part.strip() for part in [question, research_context, plan_text] if str(part or "").strip())
    result = build(project, combined_plan, repo_root=Path(repo_root))

    payload = {
        "ok": result.success,
        "message": result.message,
        "path": result.path,
        "files_written": result.files_written,
    }
    if bus is not None:
        try:
            bus.emit("make_app", "stack_builder_done", payload)
        except Exception:
            pass

    if progress_callback:
        progress_callback("stack_builder_done", payload)

    return payload


__all__ = ["BuildResult", "build", "run_stack_builder_pool"]
